project_id = "ssthzvolysdlftxunpwp"

[functions.analyze-resume]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-risk-notification]
verify_jwt = true

[functions.send-workspace-invitation]
verify_jwt = true
